CREATE DATABASE IF NOT EXISTS memory_trainer;
USE memory_trainer;

CREATE TABLE IF NOT EXISTS Cards (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL DEFAULT 'SingularisArt',
  date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  finishedTime INT UNSIGNED NOT NULL DEFAULT 60,
  score FLOAT UNSIGNED NOT NULL DEFAULT 10,
  item VARCHAR(255) NOT NULL DEFAULT 'Cards',
  numberOfItems INT UNSIGNED NOT NULL DEFAULT 52,
  actualCardData LONGTEXT NOT NULL DEFAULT '{}',
  memorizedCardData LONGTEXT NOT NULL DEFAULT '{}',
  numberOfCorrectlyMemorizedItems INT UNSIGNED NOT NULL DEFAULT 52,
  numberOfIncorrectlyMemorizedItems INT UNSIGNED NOT NULL DEFAULT 0
);
